### ISSUE TITLE
-Subclassing- Composition as a way to implement code sharing/inheritance

### ISSUE THREAD

**Issue by mattkbrown** [Keck-DataReductionPipelines/Framework#10]

**Comment by lucarizzi** [comment]
Needs to be rewritten to talk about composition instead of subclassing

**Comment by mattkbrown** [comment]
One issue with multiple inheritance, as in the kcwi_primitives class, is that there can be namespace collisions. For example, all the primitives that kcwi_primitives inherits from all inherit from BasePrimitives. In BasePrimitives, three things are defined: log, set_frame, copy_frame. This doesn't have a problem when ccd_primitives, imgmath_primitives, and proctab_primitives inherit from it, but when kcwi_primitives inherits, it gets four copies of those definitions and subsequently overwrites each one. This is fine in this case because the inherited functions are the same. However, if you accidentally write a function with the same name in two different primitive files, the one with the super() called last will be the one stored. This can lead to issues with debugging when a function is called and does not behave as expected.

Instead, since instrument-specific primitives will have many things it needs to include, composition has been proposed to handle the overlap problem. Each primitive that would be a superclass for the instrument-specific primitive class would instead become an object within the instrument-specific class with a variable acting as a namespace through which it is invoked.

**Comment by lucarizzi** [comment]
Addressed in Sec 3.2
