### ISSUE TITLE
Execution modes

### ISSUE THREAD

**Issue by mattkbrown** [Keck-DataReductionPipelines/Framework#13]
Fills REQ_12, REQ_13, REQ_14

**Comment by mattkbrown** [comment]
There will be three main execution modes for the Framework: Local User mode, Client/Server mode, and Science Platform mode.

Local User mode: This mode is made for the standard pipeline user. It is sometimes referred to as "batch mode", but that term can also be applied to the Science Platform mode. The Local User mode is primarily used to reduce a set of data that has been isolated on the user's local machine. All of the calibrations and science files will be grouped together in a folder and the framework will be directed to that folder for the files to be reduced. The local configuration file will be used in this mode so the user can set the parameters of their reduction easily. In the future, master calibration files may be available for download from KOA to reduce the amount of work the pipeline needs to do.

Server mode: This mode is made for nightly observers. The primary goal is for the framework to process files as they come in. It will have access to generic master files in order to produce quick QA plots for the science currently being taken. When the necessary calibration files are collected, it can reprocess the files for science quality reductions. Running in this mode, the user will have to access the server through a local client. That local client can be running from a WMKO computer or the user's local machine. When running in this mode, the local configuration is not used. Instead, the server will have to be configured through commands from the client. One option can be to upload the local configuration file. However, each setting should be configurable from the local client. Commands to reprocess the data with updated calibrations will also be necessary. 

Science Platform mode: When running in this mode, the user will have a workspace within a science platform (possibly KOA) where they can queue up sets of data to be reduced. The user will be able to specify which data to retrieve from the archive, process them all at once, and download the reduced data. This is similar to local user mode in that it will process the data as a batch. However, it will be similar to the server mode in that it has to be configurable from a client. This client could be a python program or it could be a web interface. Either way it will be done remotely.

**Comment by mattkbrown** [comment]
Science Platform mode will also allow KOA itself to reprocess data in the archive if there are updates to a pipeline.

**Comment by mattkbrown** [comment]
The default mode will be local user mode with server mode and science platform mode requiring special command invocations to run.

**Comment by mattkbrown** [comment]
Server mode at WMKO will require an authentication layer for the client so that only a user designated for the night can make changes to the configuration of the Framework. This will include observers from both Keck I and Keck II telescopes as well as any ToO observers who trigger before or during the night.

**Comment by lucarizzi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hello](https://trello.com/c/bN1bDs9u/1-hello)

**Comment by lucarizzi** [comment]
Transferred to section 1.2 of the document.
