### ISSUE TITLE
Describe stakeholders

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/Framework#5]
## Users
* science users: these are people who are trying to reduce data on a local machine under their control
* night time users: people reducing data on the fly at the telescope, probably using facility (Keck or KOA) computers
* remote users: people reducing data through a science platform (likely KOA)
* Support Astronomers or other WMKO staff doing performance tracking or quality assessments
* KOA, running the pipeline in fully automated mode for the archive

## Stakeholders
* pipeline authors: these are people who write recipes and primitives to reduce data from an instrument
* support astronomers: who will answer user questions and trouble tickets and will do some software maintenance
* software maintainers: who are not the original developers but are tasked to support the pipelines

**Comment by mattkbrown** [comment]
Added remote users: users who are doing batch processing on a remote server (like through KOA)

**Comment by lucarizzi** [comment]
Add:

- Support Astronomers or other WMKO staff doing performance tracking or quality assessments
- KOA, running the pipeline in fully automated mode for the archive

**Comment by lucarizzi** [comment]
See Sections 1.1 and 1.2
