### ISSUE TITLE
Persistent storage of intermediate steps

### ISSUE THREAD

**Issue by mattkbrown** [Keck-DataReductionPipelines/Framework#7]
Fills REQ_11a

Related to #3 and #4 (this is almost a duplicate of #4)

**Comment by mattkbrown** [comment]
When processing files, intermediate steps should be stored to prevent reprocessing of the same files. For example, if a bias has already been overscan-subtracted, it should not be overscan-subtracted again. However, if a master bias has not been created yet, the completed bias should be used to create the master bias when enough bias files have been processed.

One method of doing this would be to parse the process table for the files that have already been processed. If a reduction is interrupted, the state of the last reduction would be most recent in the process table and can be continued from there. Once the full reduction has been completed, then all the intermediate files can be deleted if the user decides to remove them.

For nightly use by observers, the intermediate files created from this process can be stored in a database (probably KOA) that will be accessible by other users. This way, when reprocessing the data for any reason a check to the database can be done for an adequate master calibration file.

**Comment by joshwalawender** [comment]
Also note that the record (i.e. the proctable) should include version information for each primitive and recipe applied to the data.  This ensures that the DRP can refuse to mix version numbers if desired, or if not, there exists a record to aid in troubleshooting.
