### ISSUE TITLE
Recipes association system

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/Framework#9]

**Comment by lucarizzi** [comment]
The recipe association system is the engine that connects a specific image type to the recipe that is necessary to process the data. While the details of the implementation can vary, we will adopt the paradigms that the association between an image type and the recipe is driven entirely by the data, without accessing additional external resources. In simple terms, this means that the FITS file itself will contain enough information to trigger the appropriate reduction steps.

One of the possible implementations of this system is to prescribe the reduction recipe as part of the data acquisition system. In this method, the FITS file would contain a direct call to a reduction recipe, with a dedicated header keyword. This method has the advantage that the association between the data and their reduction steps is fully contained in the data, increasing the reproducibility of the reduction steps. On the other hand, this method causes a direct external dependency: the name of the reduction recipe as set by the data acquisition system must match the name of a recipe in the pipeline. Obviously, the user would have the possibility of overriding the pre-set recipe using configuration parameters.

Another possible implementation is based on an association table between data type and reduction recipes. In this method, the only information provided by the data is the image type (bias, dark, flat, science etc.). The image type would be associated to a reduction recipe by means of an association table internal to the pipeline. This opens the possibility of using different association tables for different purposes. For example, a "quick-look" association table could be used to trigger quick-look recipes at night, while a "science quality" association table could be used for user-driven science quality reduction. 

A third possible implementation is based on ideas developed by the Gemini Data Reduction team and implemented in their DRAGONS system. The core idea is to have a set of tags, or properties, that enrich and characterize the data. The same tags are also exposed by each recipe. The association between the data and the recipes is produced by matching the data tags with the recipe tags. For example:
A sky flat from LRIS would be tagged as: "raw" "LRIS" "blue" "skyflat"
The reduce_lris_sky_flat recipe would expose the tags: "LRIS" "skyflat"
And the association system would use this recipe to reduce skyflats, both for blue and red side, but it would not attempt to use this recipe for DEIMOS, for example. 
This system is less direct that the one described above, and somewhat less intuitive. On the other hand, it is more flexible and makes is a more natural way of discovering the list of possible recipes: essentially all the recipes are always available, regardless of their specific location in terms of directories or association to an instrument.
It also offers a different approach to running the pipeline in different modes. For example, there could be two reduce_lris_science_quick and reduce_lris_science_full recipes, doing different things and differentiated by a "quick" and "full" tag. The choice of which recipe to run could be triggered by a command line argument or by the environment (WMKO night time vs. KOA vs. single user) which causes the "quick" or "full" tags to be added to the data at load time.

**Comment by joshwalawender** [comment]
Of the three strategies described above: 1) prescribe the recipe at data acquisition, 2) an association table, and 3) DRAGONS style tags, I would discourage number 3 (DRAGONS style tags) unless there are specific areas where it would offer an advantage.  Both of the other two systems are more transparent to night time users, science users, and support astronomers using the pipeline or doing support for the pipeline.
